version: '3'
services:
  mall-admin:
    image: mall/mall-admin:1.0-SNAPSHOT
    build: ../../mall-admin
    container_name: mall-admin
    ports:
      - 8080:8080
    volumes:
      - ./mydata/app/mall-admin/logs/:/var/logs/
      - ./etc/localtime/:/etc/localtime/
      - ../../../mirrorTaint.jar:/usr/local/lib/taint-agent-core-1.0.0.jar
      # - ../../../ToolAgent-1.0.jar:/usr/local/lib/ToolAgent-1.0.jar
#      - ~/.m2/repository/edu/gmu/swe/phosphor/Phosphor/0.0.5-SNAPSHOT/Phosphor-0.0.5-SNAPSHOT.jar:/tmp/Phosphor.jar
#      - ../../../:/phos/
      - ../../../entrypoint/entry-mall-swarm-ma.sh:/tmp/entrypoint.sh
    tmpfs:
      - /tmp:rw,noexec,nosuid
      - /tmp/caches:rw,noexec,nosuid
      - /toolAgent:rw,noexec,nosuid
    entrypoint: /tmp/entrypoint.sh
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - mysql:db #可以用db这个域名访问mysql服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
      - rabbitmq:rabbit #可以用rabbit这个域名访问rabbitmq服务

  mall-search:
    image: mall/mall-search:1.0-SNAPSHOT
    build: ../../mall-search
    container_name: mall-search
    ports:
      - 8081:8081
    volumes:
      - ./mydata/app/mall-search/logs/:/var/logs/
      - ./etc/localtime/:/etc/localtime/
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
      - mysql:db #可以用db这个域名访问mysql服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  mall-portal:
    image: mall/mall-portal:1.0-SNAPSHOT
    build: ../../mall-portal
    container_name: mall-portal
    ports:
      - 8085:8085
    volumes:
      - ./mydata/app/mall-portal/logs/:/var/logs/
      - ../../../mirrorTaint.jar:/usr/local/lib/taint-agent-core-1.0.0.jar
      # - ../../../ToolAgent-1.0.jar:/usr/local/lib/ToolAgent-1.0.jar
#      - ~/.m2/repository/edu/gmu/swe/phosphor/Phosphor/0.0.5-SNAPSHOT/Phosphor-0.0.5-SNAPSHOT.jar:/tmp/Phosphor.jar
#      - ../../../:/phos/
      - ../../../entrypoint/entry-mall-swarm-mp.sh:/tmp/entrypoint.sh
    tmpfs:
      - /tmp:rw,noexec,nosuid
      - /tmp/caches:rw,noexec,nosuid
      - /toolAgent:rw,noexec,nosuid
    entrypoint: /tmp/entrypoint.sh
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - mongo:mongo #可以用mongo这个域名访问mongo服务
      - mysql:db #可以用db这个域名访问mysql服务
      - rabbitmq:rabbit #可以用rabbit这个域名访问rabbitmq服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  mall-auth:
    image: mall/mall-auth:1.0-SNAPSHOT
    build: ../../mall-auth
    container_name: mall-auth
    ports:
      - 8401:8401
    volumes:
      - ./mydata/app/mall-auth/logs/:/var/logs/
      #- ./etc/localtime/:/etc/localtime/
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  mall-gateway:
    image: mall/mall-gateway:1.0-SNAPSHOT
    build: ../../mall-gateway
    container_name: mall-gateway
    ports:
      - 8201:8201
    volumes:
      - ./mydata/app/mall-gateway/logs/:/var/logs/
      #- ./etc/localtime/:/etc/localtime/
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
#  mall-monitor:
#    image: mall/mall-monitor:1.0-SNAPSHOT
#    build: ../../mall-monitor
#    container_name: mall-monitor
#    ports:
#      - 8101:8101
#    volumes:
#       - ./mydata/app/mall-monitor/logs/:/var/logs/
#      #- ./etc/localtime/:/etc/localtime/
#    environment:
#      - 'TZ="Asia/Shanghai"'
#    external_links:
#      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务